version: '3.7'
services:
  cron:
    image: fballiano/magento2-cron
    depends_on:
      - apache
      - varnish
    links:
      - db
      - cache
      - sessions
      - clusterdata
      - apache
      - varnish
    volumes:
      - type: bind
        source: ./magento2
        target: /var/www/html
        consistency: delegated
      - type: bind
        source: ./varnish.secret
        target: /varnish.secret
        consistency: consistent
      # Enable the next line if you want to add a custom php.ini
      #- ./php.ini:/usr/local/etc/php/conf.d/999-customphp.ini

  varnish:
    image: fballiano/varnish
    ports:
      - 80
      - 6082:6082
    depends_on:
      - apache
    links:
      - apache
    volumes:
      - ./varnish.vcl:/etc/varnish/default.vcl
      - ./varnish.secret:/etc/varnish/secret
    environment:
      - CACHE_SIZE=256M
      - VIRTUAL_HOST=${APP_DOMAIN}
    networks:
      - default
      - nginx-proxy

  apache:
    build:
      context: ./docker/apache
    depends_on:
      - db
      - cache
      - clusterdata
    links:
      - db
      - cache
      - sessions
      - clusterdata
    environment:
      - BASE_URL=http://${APP_DOMAIN}
    volumes:
      - type: bind
        source: ./magento2
        target: /var/www/html
        consistency: delegated
      - type: bind
        source: ./magento2-install.sh
        target: /magento2-install.sh
        consistency: delegated
      - type: bind
        source: ./magento2-setup.sh
        target: /magento2-setup.sh
        consistency: delegated
      - ~/.composer/auth.json:/root/.composer/auth.json
      # Enable the next line if you want to add a custom php.ini
      #- ./php.ini:/usr/local/etc/php/conf.d/999-customphp.ini

  db:
    image: mariadb
    ports:
      - "3336:3306"
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql
        consistency: delegated
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2

  cache:
    image: fballiano/redis-volatile

  clusterdata:
    image: fballiano/redis-volatile

  sessions:
    image: redis

volumes:
  dbdata:

networks:
  nginx-proxy:
    external: true
